### ISSUE TITLE
查询 `pilled` 这个词会panic

### ISSUE THREAD

**Issue by MapoMagpie** [Karmenzind/kd#34]
初次使用时查询的词是 `pilled`，结果就直接报错了，客户端返回 

`☣ ERROR: 解析daemon返回结果失败: unexpected end of JSON input`

后面查询其他词都正常，包括 `pill` 这个词。
我以为某些词加了 `ed` 后会报错，试了不少词加上 `ed` 都没问题。
然后尝试自行编译，结果查询 `pilled` 还是报错。
然后我又删除了缓存，问题依旧，甚至查询 `pill` 这个词也会报错。

kd-server的报错:

```
≫  Received: {"Action":"query","B":{"Query":"pilled","Prompt":"","IsEN":true,"IsPhrase":false,"Output":"","Found":false,"IsLongText":false,"MachineTrans":""}}


panic: runtime error: slice bounds out of range [2:1]

goroutine 53 [running]:
github.com/Karmenzind/kd/internal/query.(*YdResult).parseCollins(0xc000141d40)
	/home/mapo-magpie/code/kd/internal/query/youdao.go:105 +0x1176
github.com/Karmenzind/kd/internal/query.FetchOnline(0xc000192200)
	/home/mapo-magpie/code/kd/internal/query/online.go:128 +0x205
github.com/Karmenzind/kd/internal.handleClient({0xb40618, 0xc000124080})
	/home/mapo-magpie/code/kd/internal/server.go:83 +0x475
created by github.com/Karmenzind/kd/internal.StartServer in goroutine 1
	/home/mapo-magpie/code/kd/internal/server.go:54 +0x4cb
```

**Comment by Karmenzind** [comment]
收到，谢谢反馈
